# Generated by Django 5.0.6 on 2024-06-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('youtube_img', models.CharField(max_length=600)),
                ('youtube_url', models.CharField(max_length=600)),
            ],
        ),
    ]
