# Generated by Django 5.0.6 on 2024-06-08 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardChoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='card',
            name='youtube_img',
            field=models.URLField(max_length=600),
        ),
        migrations.AlterField(
            model_name='card',
            name='youtube_url',
            field=models.URLField(max_length=600),
        ),
        migrations.AddField(
            model_name='card',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cards.cardchoices'),
            preserve_default=False,
        ),
    ]
